# Generated by Django 4.2 on 2023-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=14, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
