# Generated by Django 4.2 on 2023-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='phone',
            field=models.CharField(max_length=14, null=True, verbose_name='Telefon'),
        ),
    ]
