# Generated by Django 4.2 on 2023-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_basket_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='phone',
            field=models.CharField(default=1, max_length=14, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
