# Generated by Django 4.2 on 2023-04-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_basket_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='phone',
        ),
    ]
